# Utiliser une image Node.js officielle
FROM node:18

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de configuration
COPY package.json package-lock.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers d'application
COPY . .

# Exposer le port 3000 pour l'API et WebSocket
EXPOSE 3000

# Lancer le serveur
CMD ["node", "server.js"]
